//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMaps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string Code { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Name { get; set; }
        public string contactperson { get; set; }
        public Nullable<double> warada { get; set; }
        public string subcity { get; set; }
        public string district { get; set; }
        public Nullable<double> telephone { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public int id { get; set; }
    }
}
